development:
  adapter: postgresql
  database: deals
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: deals
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: deals
  pool: 5
  timeout: 5000
